name: Page Speed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Screenshot
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.screenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGE_SPEED_API_KEY }}
          plugin_pagespeed_url: https://elc.github.io
